name: Testing docker build

on:
  workflow_dispatch:
  push:
    # trigger only on main branch
    branches:
      - main
    # trigger only on changes to the following files
    paths:
      - "{{cookiecutter.package_import_name}}/src/**"
      - "{{cookiecutter.package_import_name}}/poetry.lock"
      - "{{cookiecutter.package_import_name}}/pyproject.toml"
      - "environment.yml"
      - "requirements.txt"
      - "Dockerfile"
      - ".github/workflows/docker.yml"
  pull_request:
    # trigger only on main branch
    branches:
      - main
    # trigger only on changes to the following files
    paths:
      - "{{cookiecutter.package_import_name}}/src/**"
      - "{{cookiecutter.package_import_name}}/poetry.lock"
      - "{{cookiecutter.package_import_name}}/pyproject.toml"
      - "environment.yml"
      - "requirements.txt"
      - "Dockerfile"
      - ".github/workflows/docker.yml"

jobs:
  docker-build:
    runs-on: ubuntu-20.04
    steps:
      - # get repository code
        name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build the image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          tags: {{cookiecutter.package_name}}:latest
          {% raw -%}
          cache-from: type=gha, scope=${{ github.workflow }}
          cache-to: type=gha, mode=max, scope=${{ github.workflow }}
          {%- endraw %}
