name: Publish a docker image

on:
  release:
    types:
      - published

jobs:
  docker-push:
    runs-on: ubuntu-20.04
    permissions:
      contents: read
      packages: write
    steps:
      - # get repository code
        name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          {% raw -%}
          key: ${{ runner.os }}-buildx
          {%- endraw %}
      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          {% raw -%}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          {%- endraw %}
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ghcr.io/{{cookiecutter.repo_author}}/{{cookiecutter.package_name}}:latest,ghcr.io/{{cookiecutter.repo_author}}/{{cookiecutter.package_name}}:{% raw %}${{ github.event.release.tag_name }}{% endraw %}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new
      - # Temp fix
        # https://github.com/docker/build-push-action/issues/252
        # https://github.com/moby/buildkit/issues/1896
        name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
