name: Draft

on:
  workflow_dispatch:
  push:
    # trigger only on main branch
    branches:
      - main
    # trigger only on changes to the following files
    paths:
      - "{{cookiecutter.package_import_name}}/src/**"
      - "{{cookiecutter.package_import_name}}/LICENSE"
      - "{{cookiecutter.package_import_name}}/README.md"
      - "{{cookiecutter.package_import_name}}/poetry.lock"
      - "{{cookiecutter.package_import_name}}/pyproject.toml"
      - ".github/workflows/draft.yml"
      - ".github/release-drafter.yml"

jobs:
  draft:
    name: Update draft release
    # better to use pinned version here
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v5
        with:
          config-name: release-drafter.yml
          disable-autolabeler: true
        env:
          {% raw -%}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          {%- endraw %}
